### PR TITLE
Try to run the tests on MacOS and Windows too.

### PR DESCRIPTION
**Pull request by JulienPalard**

### CODE REVIEW

**Comment by aroberge** [comment]
For simplicity, I just merged the changes ... but will revert the coveragerc deletion (and removed the coverage information from tox). This is because I do not use tox: I create various virtual environments locally and navigate between them to do simple tests. I do include Python 3.10 (even when it was in alpha) in some tests.  I have a few .bat files that I use for various tests.

**Comment by JulienPalard** [comment]
> This is because I do not use tox: I create various virtual environments locally and navigate between them to do simple tests.

coverage will still read tox.ini config even if you don't use tox, but I understand it's strange to have to modify tox.ini when you don't use it.

**Comment by aroberge** [comment]
I read the documentation [1] and found that I could specify tox.ini to be used as a configuration file.  I did that this morning ... and the reported coverage went down :(.  I'm guessing that it didn't combine the results from running with different Python versions.  This is the second time that I see what looks like an allowed flag not do what it is supposed to do. I'm using the pytest-cov plugin.  I'll just stick to using coveragerc.

[1] Yes, I know, it is shocking!

**Comment by aroberge** [comment]
Can't run tox on Windows on Github for py36 for friendly:
```
ERROR: invocation failed (exit code 1), logfile: D:\a\friendly\friendly\.tox\py36\log\py36-5.log
  File "c:\hostedtoolcache\windows\python\3.9.5\x64\lib\site-packages\tox\session\__init__.py", line 225, in subcommand_test
    run_sequential(self.config, self.venv_dict)
  File "c:\hostedtoolcache\windows\python\3.9.5\x64\lib\site-packages\tox\session\commands\run\sequential.py", line 9, in run_sequential
    if venv.setupenv():
  File "c:\hostedtoolcache\windows\python\3.9.5\x64\lib\site-packages\tox\venv.py", line 656, in setupenv
    envlog.set_python_info(command_path)
  File "c:\hostedtoolcache\windows\python\3.9.5\x64\lib\site-packages\tox\logs\env.py", line 18, in set_python_info
    answer["executable"] = python_executable
TypeError: 'NoneType' object does not support item assignment
================================== log start ==================================

=================================== log end ===================================
\u2716 FAIL py36 in 6.483 seconds\r\n\u2714 OK flake8 in 16.205 seconds\r\n\u2714 OK black in 26.031 seconds\r\n\u2714 OK py39 in 28.993 seconds\r\n\u2714 OK py37 in 35.534 seconds\r\n\u2714 OK py38 in 39.104 seconds\r\n\u2714 OK coverage in 1.584 seconds\r\n___________________________________ summary ___________________________________
ERROR:   py36: parallel child exit code 1
  py37: commands succeeded
  py38: commands succeeded
  py39: commands succeeded
  flake8: commands succeeded
  black: commands succeeded
  coverage: commands succeeded
Error: Process completed with exit code 1.
```

**Comment by JulienPalard** [comment]
This is a known tox issue: https://github.com/tox-dev/tox/issues/1570

I don't know how it passes on github actions, it was failing a few month ago...

**Pull request merged**
